import Head from 'next/head'
import Image from 'next/image'
import { Inter, Aladin } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useMutation, useQuery } from '@tanstack/react-query'
import { deleteUser, fetchUsers } from '@/helper/api/users'
import { Table } from '@/components'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })
const aladin = Aladin({ subsets: ['latin'], display: "auto",weight: "400" })

export default function Home() {
  
  const {data, error, isLoading} = useQuery({
    queryKey:["user"],
    queryFn: () => fetchUsers(),
  })
  
  const {mutate} = useMutation({
    mutationFn: (id) => data.filter((el)=> el !== id)
  })
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        
        <Table columns={[
          {key:"id", title:"id"},
          {key:"name", title:"name"},
          {key:"email", title:"email"},
          {key:"id", title:"Action", render: (val) => <>
          <button onClick={()=> mutate(val.id)}>Delete</button>
          <Link href={`/${val.id}`} >Link</Link>
          </>}
        ]} data={data} />
        
      </main>
    </>
  )
}
